#%RAML 1.0
title: Kay-Knows
baseUri: https://localhost:4200
mediaType:  application/json
documentation:
  - title: Welcome
    content: |
      Welcome to the API Documentation for the Kay-Knows Career Tree application.
types: 
  family:
    type: object
    properties: 
      family_id:
        type: number
        required: true
      family_name:
        type: string
        required: true
  capability:
    type: object
    properties: 
      capability_id:
        type: number
        required: true
      capability_name:
        type: string
        required: true
      family_id:
        type: number
        required: true
  band:
    type: object
    properties: 
      band_id:
        type: number
        required: true
      band_name:
        type: string
        required: true
  role:
    type: object
    properties: 
      role_id:
        type: number
        required: true
      role_name:
        type: string
        required: true
      capability_id:
        type: number
        required: true
      family_id:
        type: number
        required: true
      band_id:
        type: number
        required: true
      role_spec:
        type: string
        required: true
      role_description:
        type: string
        required: true
  capability_lead:
    type: object
    properties: 
      capability_lead_id:
        type: number
        required: true
      user_id:
        type: number
        required: true
      capability_id:
        type: number
        required: true
      capability_lead_photo:
        type: string
        required: false;
      capability_lead_message:
        type: string
        required: true


/all:
  description: Get all the information in a flat format
  get:
    responses: 
      200:
        body: 
          application/json:
            type: |
              [{
                "capability_id": number,
                "family_id": number,
                "family_name": string,
                "capability_name": string,
                "role_id": number,
                "role_name": string,
                "band_id": number,
                "band_name": string
              }]
            example:
              [{
                "capability_id": 1,
                "family_id": 1,
                "family_name": "Family Name",
                "capability_name": "Capability Name",
                "role_id": 3,
                "role_name": "Role Name",
                "band_id": 3,
                "band_name": "Band 3 Name"                
              },
              {
                "capability_id": 2,
                "family_id": 2,
                "family_name": "Family 2 Name",
                "capability_name": "Capability 2 Name",
                "role_id": 2,
                "role_name": "Role 2 Name",
                "band_id": 3,
                "band_name": "Band 3 Name"                
              }]
/families:
  description: Endpoint for getting all families
  get:
    responses: 
      200:
        body: 
          application/json:
            type: family[]
            example:
              -
                family_id: 1
                family_name: "Family Name"
              -
                family_id: 2,
                family_name: "Family 2 Name"
/capabilities:
  description: Endpoint for getting all capabilities
  get:
    responses:
      200:
        body: 
          application/json:
            type: capability[]
            example:
              -
                capability_id: 1
                capability_name: "Cap name 1"
                family_id: 1
              -
                capability_id: 2
                capability_name: "Cap name 2"
                family_id: 2
  /{family_id}:
    description: Filter all the capabilities by the family_id
    uriParameters:
      family_id: 
        type: number
        description: Identifier for the family to filter by
    get:
      responses: 
        200:
          body: 
            application/json:
              type: capability[]
              example:
                -
                  capability_id: 1
                  capability_name: "Cap name 1"
                  family_id: 1
                -
                  capability_id: 2
                  capability_name: "Cap name 2"
                  family_id: 2
/bands:
  description: Endpoint for getting all bands
  get:
    responses:
      200:
        body:
          application/json:
            type: band[]
            example:
              -
                band_id: 1,
                band_name: "Band 1"
              -
                band_id: 2,
                band_name: "Band 2"
/roles:
  description: Endpoint for getting all roles
  get:
    responses:
      200:
        body:
          application/json:
            type: role[]
            example:
              -
                role_id: 1
                role_name: "Role 1"
                capability_id: 1
                family_id: 1
                role_spec: "url://to/sharepoint/document"
                role_description: "A long description of up to 500 characters"
              -
                role_id: 2
                role_name: "Role 2"
                capability_id: 1
                family_id: 1
                role_spec: "url://to/sharepoint/another/document"
                role_description: "A longer description of up to 500 characters"
/capability-leads:
  description: Endpoint for getting all capabily leads
  get:
    responses: 
      200:
        body: 
          application/json:
            type: capability_lead[]
            example:
              -
                capability_lead_id: 1
                user_id: 2
                capability_id: 3
                capability_lead_photo: "url://to/capability/lead/photo"
                capability_lead_message: "A nice message from the lead"
  /{capability_id}:
    description: Filter all the capability leads by the capability_id
    uriParameters:
      capability_id: 
        type: number
        description: Identifier for the capbility to filter by
    get:
      responses: 
        200:
          body: 
            application/json:
              type: capability_lead[]
              example:
                -
                  capability_lead_id: 1
                  user_id: 2
                  capability_id: 3
                  capability_lead_photo: "url://to/capability/lead/photo"
                  capability_lead_message: "A nice message from the lead"
